using System.Collections;
using UnityEngine;
using UnityEngine.UI;

public class CameraFadeController : MonoBehaviour
{
    [Header("Fade Settings")]
    [SerializeField] private Image fadeImage;
    [SerializeField] private float fadeDuration = 1f;

    [Header("Black Screen Hold")]
    [SerializeField] private float blackHoldDuration = 0f;

    [Header("Automatic Page Transition Fade")]
    [Tooltip("Displayed Page 13 = Index 12")]
    [SerializeField] private int page13Index = 12;

    [Tooltip("Displayed Page 14 = Index 13")]
    [SerializeField] private int page14Index = 13;

    [Header("First Page 14 Visit")]
    [Tooltip("If enabled, the first visit to Page 14 will not trigger a fade.")]
    [SerializeField] private bool ignoreFirstPage14Fade = true;

    private Coroutine fadeCoroutine;

    private int previousPageIndex = -1;

    private bool firstPageChangeIgnored;
    private bool hasVisitedPage14;

    private void Awake()
    {
        // If the scene starts directly on Page 14,
        // count that as the first visit.
        if (PageNavigationController.CurrentIndex == page14Index)
        {
            hasVisitedPage14 = true;
        }
    }

    private void OnEnable()
    {
        PageNavigationController.OnPageChanged += HandlePageChanged;
    }

    private void Start()
    {
        // Establish the initial page.
        // No fade is allowed during initialization.
        previousPageIndex = PageNavigationController.CurrentIndex;

        // The first OnPageChanged event generated by
        // PageNavigationController.Start() must be ignored.
        firstPageChangeIgnored = false;
    }

    private void OnDisable()
    {
        PageNavigationController.OnPageChanged -= HandlePageChanged;
    }

    private void HandlePageChanged(int newPageIndex)
    {
        // ---------------------------------------------------------
        // Ignore the first OnPageChanged event.
        // This is the initialization event from PageNavigationController.
        // ---------------------------------------------------------
        if (!firstPageChangeIgnored)
        {
            previousPageIndex = newPageIndex;
            firstPageChangeIgnored = true;

            if (newPageIndex == page14Index)
            {
                hasVisitedPage14 = true;
            }

            return;
        }

        // ---------------------------------------------------------
        // Page 13 -> Page 14
        // ---------------------------------------------------------
        if (previousPageIndex == page13Index &&
            newPageIndex == page14Index)
        {
            if (ignoreFirstPage14Fade && !hasVisitedPage14)
            {
                // First actual visit to Page 14.
                // Do NOT fade.
                hasVisitedPage14 = true;
            }
            else
            {
                FadeInAndOut();
            }
        }

        // ---------------------------------------------------------
        // Page 14 -> Page 13
        // ---------------------------------------------------------
        else if (previousPageIndex == page14Index &&
                 newPageIndex == page13Index)
        {
            FadeInAndOut();
        }

        // ---------------------------------------------------------
        // Mark Page 14 as visited regardless of how it was reached.
        // ---------------------------------------------------------
        if (newPageIndex == page14Index)
        {
            hasVisitedPage14 = true;
        }

        previousPageIndex = newPageIndex;
    }

    /// <summary>
    /// Fades the screen to black, holds for the configured duration,
    /// then fades back to transparent.
    /// </summary>
    public void FadeInAndOut()
    {
        StartFadeSequence(fadeDuration, blackHoldDuration);
    }

    /// <summary>
    /// Fades the screen to black, holds for the specified duration,
    /// then fades back to transparent.
    /// </summary>
    public void FadeInAndOut(float duration)
    {
        StartFadeSequence(duration, blackHoldDuration);
    }

    /// <summary>
    /// Fades the screen to black, holds for the specified duration,
    /// then fades back to transparent.
    /// </summary>
    public void FadeInAndOut(float fadeTime, float holdDuration)
    {
        StartFadeSequence(fadeTime, holdDuration);
    }

    private void StartFadeSequence(float fadeTime, float holdDuration)
    {
        if (fadeImage == null)
        {
            Debug.LogWarning(
                $"{nameof(CameraFadeController)}: Fade Image is not assigned.",
                this
            );

            return;
        }

        if (fadeCoroutine != null)
        {
            StopCoroutine(fadeCoroutine);
        }

        fadeCoroutine = StartCoroutine(
            FadeSequenceRoutine(
                Mathf.Max(0f, fadeTime),
                Mathf.Max(0f, holdDuration)
            )
        );
    }

    private IEnumerator FadeSequenceRoutine(float fadeTime, float holdDuration)
    {
        // Transparent -> Black
        yield return FadeRoutine(1f, fadeTime);

        // Hold on black
        if (holdDuration > 0f)
        {
            yield return new WaitForSecondsRealtime(holdDuration);
        }

        // Black -> Transparent
        yield return FadeRoutine(0f, fadeTime);

        fadeCoroutine = null;
    }

    private IEnumerator FadeRoutine(float targetAlpha, float duration)
    {
        Color color = fadeImage.color;
        float startAlpha = color.a;

        if (duration <= 0f)
        {
            color.a = targetAlpha;
            fadeImage.color = color;
            yield break;
        }

        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.unscaledDeltaTime;

            float progress = Mathf.Clamp01(elapsed / duration);

            color.a = Mathf.Lerp(
                startAlpha,
                targetAlpha,
                progress
            );

            fadeImage.color = color;

            yield return null;
        }

        color.a = targetAlpha;
        fadeImage.color = color;
    }
}